---
title: "titanic_data_new_viz"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```



```{r setup, include=FALSE}

# Set the working directory
 setwd("E:/Documents/Data Science/UDACITY_Data Analyst Nanodegree/Core/7. Data Visualization/9. Project- make effective visualization/Project_HB_data_viz")
 
### Reading in Data
titanic_data_new <- read.csv('titanic_data.csv')

### Subseting 
titanic_data_new <- subset(titanic_data, Survived == 1)
titanic_data_new <- subset(titanic_data_new, Embarked == "C" | Embarked == "Q" | Embarked ==  "S")

### Changing factor levels
titanic_data_new$Pclass[titanic_data_new$Pclass == 1] <- 'First Class'
titanic_data_new$Pclass[titanic_data_new$Pclass == 2] <- 'Second Class'
titanic_data_new$Pclass[titanic_data_new$Pclass == 3] <- 'Third Class'

levels(titanic_data_new$Embarked)[match("C",levels(titanic_data_new$Embarked))] <- 'Cherbourg'
levels(titanic_data_new$Embarked)[match("Q",levels(titanic_data_new$Embarked))] <- 'Queenstown'
levels(titanic_data_new$Embarked)[match("S",levels(titanic_data_new$Embarked))] <- "Southampton"

#Omit NA
titanic_data_new <-na.omit(titanic_data_new) # removing NA

## Subsetting for only important columns
titanic_data_new <- titanic_data_new[,c( 2, 3, 5, 6, 10, 12)]


# Using cut
Age_Bucket <- cut(titanic_data_new$Age, 
                       breaks = c(-Inf, 19, 41, 61, Inf), 
                       labels = c("Children (0-18)", "Young (19-40)","Middle-Aged (41-60)", "Senior-Citizen   (61-above)"), 
                       right = FALSE)

head(titanic_data_new)## checking changes made

# Write CSV in R
write.csv(titanic_data_new, file = "titanic_data_1.csv")

```
